# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Dâmaso Júnio Pereira Brasileo
title: Software Engineering Student
email: junio.pereirab@gmail.com
website: www.github.com/juniopereirab/myresume

# Social links
twitter_username: damasuj
github_username:  juniopereirab
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: juniobrasileo
linkedin_username: dâmaso-júnio-pereira-brasileo-6711a4a0
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dâmaso and I'm a software engineering student at Universidade de Brasilia. As well as study I also participe in some projects at UnB, and also work as a Computing Teacher. I have worked at some groups and subjects gaining teamwork experiences.

  I am most skilled in: <mark>Software Documentation</mark> and <mark>Playing Games</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Although my interests in networks and software engineering some of my other interests and hobbies are:
   - Playing MOBA Games
   - Photography
   - Dancing
   - Spend time with friends

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
